---
ansible_port: 22
ansible_user: ubuntu
k3s_version: v1.30.2+k3s1
    # The token should be a random string of reasonable length. You can generate
    # one with the following commands:
    # - openssl rand -base64 64
    # - pwgen -s 64 1
    # You can use ansible-vault to encrypt this value / keep it secret.
token: "gPsqV4QMSXI/8La1+tpnfEiYT1hEXSEaEjhDuWOm+dtFjPvxAESLfTZAgQH2mCAC"
api_endpoint: "{{ hostvars[groups['server'][0]]['ansible_host'] | default(groups['server'][0]) }}"
extra_server_args: ""
extra_agent_args: ""
